import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import AuthProvider from '@/context/AuthProvider'
import LayoutProvider from '@/context/LayoutProvider'
import getCurrentUser from '@/actions/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const currentUser = await getCurrentUser()
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <LayoutProvider currentUser={currentUser}>{children}</LayoutProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
